sudo: required
services:
  - docker

before_install:
  - docker build -t mounirabdous/docker-tuto -f Dockerfile.dev .

script:
  - docker run -e CI=true mounirabdous/docker-tuto npm run test -- --coverage