sudo: required
services:
  - docker

before_install:
  - docker build -t mounirabdous/docker-tuto -f Dockerfile.dev .

script:
  - docker run mounirabdous/docker-tuto ./node_modules/.bin/react-scripts test --coverage